### ISSUE TITLE
fail to deploy the private contract to the quorum by using truffle

### ISSUE THREAD

**Issue by zhj4655** [jpmorganchase/quorum-examples#102]
2_deploy_simplestorage.js:
```
var simple_storage = artifacts.require("SimpleStorage");

module.exports = function(deployer) {
    deployer.deploy(simple_storage, 123, {privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});
};
```

and the error:
```
Running migration: 2_deploy_simplestorage.js
  Replacing SimpleStorage...
  ... 0x02362d96174a5d484afb7dfaa433347caa659b9f5a316ff028734053cca5f476
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:327595:46)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:37991:25
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:329533:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:176186:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:325200:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:328229:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176415:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176705:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176860:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176820:24)

```
But when remove the {privateFor:["  "]} in 2_deploy_simplestorate.js, it works
I don`t know why the private transaction not work.
although the deploy failed, a new transaction and a new block generated .
I need help.

**Comment by fixanoid** [comment]
Hi @zhj4655 we seem to currently have an issue with latest versions of truffle running latest solidity. If you downgrade to solidity 0.4.18 the problem should go away.

**Comment by zhj4655** [comment]
I didn't use the latest version
```
Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)
```
I try to down grade the truffle to 3.2.1, and use the solidity 0.4.18, but  it also has the same problem
the contract:
```
pragma solidity ^0.4.18;

contract simplestorage {
  uint public storedData;

  function simplestorage(uint initVal) public {
    storedData = initVal;
  }

  function set(uint x) public {
    storedData = x;
  }

  function get() constant public returns(uint retVal) {
    return storedData;
  }
}
```
and the deploy file 
```
var simple_storage = artifacts.require("SimpleStorage");

module.exports = function(deployer) {
    deployer.deploy(simple_storage, 123, {privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});
};
```
