### ISSUE TITLE
 Standard loadScript private-contract.js example does not work  but public-contract.js  is ok

### ISSUE THREAD

**Issue by kevinsir** [jpmorganchase/quorum-examples#186]
Environment: docker

1. [First step]
change QUORUM_CONSENSUS=raft
install example docker-compose up -d
use 7 nodes
2. [Second step]
docker exec -it quorum-examples_node1_1 geth attach /qdata/dd/geth.ipc

Welcome to the Geth JavaScript console!

instance: Geth/node1-raft/v1.8.18-stable-30d4d724(quorum-v2.2.4)/linux-amd64/go1.11.11
coinbase: 0xed9d02e382b34818e88b88a309c7fe71e65f419d
at block: 2 (Sat, 15 Aug 49576086759 13:13:35 UTC)
 datadir: /qdata/dd
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 raft:1.0 rpc:1.0 txpool:1.0 web3:1.0
3. [and so on...]
> loadScript('/examples/private-contract.js')
#### Error Logs
> loadScript('/examples/private-contract.js')
err creating contract Error: Non-200 status code: &{Status:400 Bad Request StatusCode:400 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Type:[text/plain] Content-Length:[73] Server:[Jetty(9.4.z-SNAPSHOT)] Date:[Tue, 30 Jul 2019 06:48:39 GMT]] Body:0xc02b9669c0 ContentLength:73 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc0004a2000 TLS:<nil>}
true
#### Backtrace
````
[backtrace]
````

**Comment by prd-fox** [comment]
This error indicates an issue with the transaction manager (Tessera). Can you provide some logs from the Tessera container? i.e. the output of `docker logs quorum-examples_txmanager1_1`, thanks!

**Comment by kevinsir** [comment]
docker logs quorum-examples_txmanager1_1
Here is the log  thanks
12:13:44.594 [pool-2-thread-1] ERROR c.q.t.t.TesseraScheduledExecutor - Error when executing action PartyInfoPoller
12:13:44.595 [pool-2-thread-1] ERROR c.q.t.t.TesseraScheduledExecutor - Error when executing action
javax.ws.rs.ProcessingException: java.net.UnknownHostException: txmanager3
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753) ~[tessera-app.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[tessera-app.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[tessera-app.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229) ~[tessera-app.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351) ~[tessera-app.jar:na]
        at com.quorum.tessera.client.PostDelegate.doPost(PostDelegate.java:39) ~[tessera-app.jar:na]
        at com.quorum.tessera.client.RestP2pClient.getPartyInfo(RestP2pClient.java:23) ~[tessera-app.jar:na]
        at com.quorum.tessera.node.PartyInfoPoller.pollSingleParty(PartyInfoPoller.java:75) ~[tessera-app.jar:na]
        at com.quorum.tessera.node.PartyInfoPoller.lambda$run$1(PartyInfoPoller.java:54) ~[tessera-app.jar:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_212]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_212]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_212]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[na:1.8.0_212]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_212]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_212]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_212]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_212]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_212]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_212]
        at com.quorum.tessera.node.PartyInfoPoller.run(PartyInfoPoller.java:57) ~[tessera-app.jar:na]
        at com.quorum.tessera.threading.TesseraScheduledExecutor.lambda$start$0(TesseraScheduledExecutor.java:50) ~[tessera-app.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: java.net.UnknownHostException: txmanager3
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_212]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_212]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_212]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[na:1.8.0_212]
        at org.glassfish.jersey.client.internal.HttpUrlConnector.lambda$_apply$0(HttpUrlConnector.java:382) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:195) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:189) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:208) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:295) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.ByteArrayProvider.writeTo(ByteArrayProvider.java:97) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.ByteArrayProvider.writeTo(ByteArrayProvider.java:61) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163) ~[tessera-app.jar:na]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:516) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:498) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:384) ~[tessera-app.jar:na]
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282) ~[tessera-app.jar:na]
        ... 32 common frames omitted

**Comment by kevinsir** [comment]
However the public contract is right
> loadScript('/examples/public-contract.js')
Contract transaction send: TransactionHash: 0x84cefc3aab8ce5797dc73c70db604e5c8830fc7c2cf215876eb34fff533e2725 waiting to be mined...
true
>

**Comment by prd-fox** [comment]
The public contracts will be fine since the issue is with the private transaction manager.

For some reason, Tessera is not able to resolve hostnames, so cannot find the other containers that it needs to talk too. Have you changed the default DNS settings for Docker?

**Comment by kevinsir** [comment]
No,I never change it. And try dock-compose down then up for many times. It has the same problem.Maybe, change the hosts file will be fine ?

**Comment by prd-fox** [comment]
It could probably work. Alternatively, you can edit the `docker-compose.yml` where it creates the Tessera peers (lines 149 -171), and replace each txmanager hostname with its IP address.

Still, it is usually good to know the root cause, but I can't can't think of anything other than a non-default setup.

**Comment by kevinsir** [comment]
Yeah,it works! Thanks. I think maybe the txmanager  not written in the hosts file. It is only  '172.16.239.101 txmanager1' in the docker of quorum-examples_txmanager1_1's host file, not all of them.
