### ISSUE TITLE
7nodes example raft-start.sh error

### ISSUE THREAD

**Issue by pablovillot** [jpmorganchase/quorum-examples#63]
After running raft-init.sh without problems if I run raft-start.sh, it returns the following error:

```
./raft-start.sh
[*] Starting Constellation nodes
[*] Starting node 1 (permissioned)
[*] Starting node 2 (permissioned)
[*] Starting node 3 (permissioned)
[*] Starting node 4 (permissioned)
[*] Starting node 5 (unpermissioned)
[*] Starting node 6 (unpermissioned)
[*] Starting node 7 (unpermissioned)
[*] Waiting for nodes to start
[*] Sending first transaction
panic: MustNew error: Get http+unix://c/upcheck: dial unix: missing address

goroutine 1 [running]:
panic(0xc1f6e0, 0xc4201d8b70)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/private/constellation.MustNew(0xc42000e00f, 0x8, 0xc42000e00f)
        /quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:76 +0x114
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0xd5a99d, 0xe, 0x1538f40, 0xc420047ea0)
        /quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:19 +0x52
github.com/ethereum/go-ethereum/private.init()
        /quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:22 +0x67
github.com/ethereum/go-ethereum/core.init()
        /quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm_env.go:165 +0xf4
github.com/ethereum/go-ethereum/cmd/utils.init()
        /quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/version.go:65 +0x76
main.init()
        github.com/ethereum/go-ethereum/cmd/geth/_obj/_cgo_import.go:6 +0x58

```

Am i missing something?

**Comment by macro88** [comment]
looks like it is failing the constellation "upcheck". 

You can call the public api or private api `curl http://localhost:9001/upcheck` or `curl --unix-socket /path/to/your/constellation.ipc "http://c/upcheck"`

Check out the logs for constellation to see why/if it is failing

Hope this helps

**Comment by patrickmn** [comment]
Please try again with the latest quorum-examples.
